name: PR Check

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Python set-up
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.4"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 isort pytest

      - name: Run unit tests
        run: pytest
