name: PR Check

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Python set-up
          uses: actions/setup-python@v2
          with:
            python-version: 3.10.4

        - name: Install Flake8
          run: pip install flake8

        - name: Run linting
          run: flake8 --config tox.ini

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Python set-up
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4

      - name: Install dependencies
        run: make local-setup

      - name: Run tests
        run: make run-tests
